export const CART = {
	PUSH_PRODUCT_TO_CART: 'PUSH_PRODUCT_TO_CART',
	INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
	SET_CART_ITEMS: 'SET_CART_ITEMS',
	SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS',
}

export const PRODUCTS = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	DECREMENT_PRODUCT_INVENTORY: 'DECREMENT_PRODUCT_INVENTORY',
}
